### ISSUE TITLE
Should I close mirrors.omsinchan.ac.th? 

### ISSUE THREAD

**Issue by kaozaza2** [termux/termux-tools#134]
After I made mirrors.omsinchan.ac.th available, many people tried to attack my college website, should I disable it to prevent attack on my college website? Or is there a better way or solution?

**Comment by MyDapitt** [comment]
> After I made mirrors.omsinchan.ac.th available, many people tried to attack my college website, should I disable it to prevent attack on my college website? Or is there a better way or solution?

Can I help you?
If you are using Cloudflare, you can turn on Under Attack Mode, set the firewall if your school campus website provides API.

**Comment by kaozaza2** [comment]
The website is using an old version of CMS, which makes it very vulnerable to code injection. The college has no plans to create a new website, I have to restore from backups very frequently.

**Comment by kaozaza2** [comment]
I want to create a new website, but there are so many old activity photos that it would take a lot of time to write posts and set everything up. I don’t have much time to do it, either.

**Comment by MyDapitt** [comment]
> Website is being attacked by botnets, not by people. That's pretty much common thing on the Internet nowadays. Never host vulnerable stuff in public.
> 
> Attack will continue as soon as your host is reachable by IP address.
> 
> I think publishing the mirror domain here just increased chances of discovery of your college website.
> 
> Termux package server also receives attack attempts, although they are unsuccessful.


Yes, it's the same as I used to create a repository package mirror on a DigitalOcean VPS. I used to try to turn on proxy mode on Cloudflare. It turned out that there were a lot of requests from Asia, especially from India and Indonesia. From that incident, the VPS was down for less than a week. I tried to mirror the main termux repository package using CNAME records, and yes.. THERE ARE A LOT OF REQUESTS IF YOU PLACE YOUR MIRROR IN THE ASIAN CONTINENT. There are so many botnets trying to attack the termux main repository package mirrors. That's really scary.

**Comment by kaozaza2** [comment]
After our discussion regarding the issues related to this server and other problems, we have decided to move the server from the on-premises location to the cloud soon. This may limit bandwidth and it might be necessary to disable the Termux mirror service. We will inform you if there are any further updates.

**Comment by kaozaza2** [comment]
I think I'll keep it but remove it from the list.
